### ISSUE TITLE
new error...AttributeError: 'Expr' object has no attribute 'map'. Did you mean: 'max'?

### ISSUE THREAD

**Issue by MichellePeckham** [oubino/z_disk#3]
z_disk) chbmp@UOL-L-P9H6X356VP z_disk % python scripts/pointcloud_to_image.py -x 'Group X Position' -y 'Group Y Position' -z 'Group Z Position' -bs size -hx 50 -hy 50 -hz 50 -s tab
List of files which will be converted
['data/17_Run1-640_c123_sum_X11_processed_IDL_purged_IDL_beadsremoved_grouped_peaks_nm_IDL_ASCII.txt', 'data/24_2Run1-640_c123_sum_X9_Processed_Purged_beadsremoved_Grouped_in_nm_IDL_ASCII.txt', 'data/24_5Run1-640_c123_sum_X18_Processed_Purged_Beadsremoved_Grouped_in_nm_IDL_ASCII.txt', 'data/23_1Run2-640_c123_sum_X8_processed_Purged_allbeadsremoved_IDL2_grouped_ASCII2.txt', 'data/23_1Run2-640_c123_sum_X8_processed_Purged_allbeadsremoved_IDL2_XY-Z_nm_ASCII2.txt', 'data/24_4Run1-640_c123_sum_X11_Processed_Purged_Beadsremoved_Grouped_in_nm_IDL_ASCII.txt', 'data/24_3Run1-640_c123_sum_X13_Processed_Purged_Beadsremoved_Grouped_In_nm_IDL_ASCII.txt', 'data/20_Run1-640_c123_sum_X11_Processed_Purged_beads_removed_Grouped_peaks_nm_IDL_ASCII.txt', 'data/25_1Run1-640_c123_sum_X5_processed_purged_beads_removed_ASCII_nm_grouped.txt', 'data/24_4Run2-640_c123_sum_X7_Processed_Purged_Beadsremoved_Grouped_nm_IDL_ASCII.txt', 'data/20_Run1-640_c123_sum_X15_processed_purged_allbeadsremoved_Grouped_peaks_nm_IDL__ASCII.txt', 'data/18_Run1-640_c123_sum_X10_processed_purged_beads_removed_Grouped_peaks_nm_IDL_ASCII.txt', 'data/23_3Run1-640_c123_sum_X8_processed_purged_beads_removed_ASCII_nm_grouped.txt', 'data/23_2Run1-640_c123_sum_X11_processed_purged_beadsremoved_ASCII_nm_grouped.txt', 'data/23_4Run1-640_c123_sum_X9_Processed_Purged_beadsremoved_Group_nm_ASCII.txt', 'data/17_Run21-640_c123_sum_X9_processed_purged_beads_removed_grouppeak_nm_IDL_ASCII.txt']
-- Bin sizes -- 
(50.10620140336134, 50.09746154456521, 58.30321063967399)
Traceback (most recent call last):
  File "/Users/chbmp/Documents/Janelia/z_disk/scripts/pointcloud_to_image.py", line 219, in <module>
    main()
  File "/Users/chbmp/Documents/Janelia/z_disk/scripts/pointcloud_to_image.py", line 193, in main
    item.coord_2_histo(
  File "/Users/chbmp/Documents/Janelia/z_disk/scripts/base.py", line 145, in coord_2_histo
    self._coord_2_pixel()
  File "/Users/chbmp/Documents/Janelia/z_disk/scripts/base.py", line 167, in _coord_2_pixel
    pl.col("x").map(lambda q: (q - x_min) / x_pixel_width).alias("x_pixel"),
    ^^^^^^^^^^^^^^^
AttributeError: 'Expr' object has no attribute 'map'. Did you mean: 'max'?

**Comment by oubino** [comment]
Hello, have you updated the code @MichellePeckham i.e. Git pull origin main
